{
 "title": "AWS DevOps T8",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU User Time Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Disk Space Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_filesystem_avail_bytes{device=\"tmpfs\"}[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Running Pods in Monitoring Namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace='monitoring'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Running Pods in Cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}