# Set to NodePort
service:
  type: NodePort
  nodePorts:
    grafana: "32001"
# Add Existing Prometheus Source
datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus:9090 
      isDefault: true
# Admin User with a separate secret password
admin:
  existingSecret: "grafana-admin-pw"
  existingSecretPasswordKey: password
# Feed a dashboard to Grafana
dashboardsProvider:
  enabled: true
dashboardsConfigMaps:
  - configMapName: "grafana-dash"
    fileName: grafana_dash.json