name: software_config

on: 
  workflow_dispatch:
  push:
    branches:
      - task_4

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRV }}
  SSH_PUBLIC_KEY: ${{ secrets.BASTION_SSH_PK }}

jobs:
  install_jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH passphrase
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config  # Load SSH config file from secrets to simplify the code
          chmod 600 ~/.ssh/config

      # Debug print out the added identities. This will prove SSH_AUTH_SOCK
      # is persisted across job steps
      - name: Print ssh-add identities
        run: |
          ssh-add -l

      - name: Install Jenkins
        run: |
          if ssh k3s_server "kubectl get pods -n jenkins | grep -q 'jekins'"; then
            echo "Jenkins is already deployed"
          else 
            echo "Installing Jenkins .... // ...." 
            cat ${{ github.workspace }}/jenkins_install_dummy.sh | ssh k3s_server 'bash -s'
          fi;