name: software_config

on: 
  workflow_dispatch:
  push:
    branches:
      - task_4

env:
  SSH_PUBLIC_KEY: ${{ secrets.BASTION_SSH_PK }}
  SSH_PRIVATE_KEY: ${{ secrets.BASTION_SSH_PRV }}

jobs:
  install_jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Proxyjump Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRV }}" > ~/.ssh/key_rsa
          chmod 400 ~/.ssh/key_rsa
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config  # Load SSH config file from secrets to simplify the code
          chmod 600 ~/.ssh/config

      - name: Install Jenkins
        run: |
          if ssh k3s_server "kubectl get pods -n jenkins | grep -q 'jenkins'"; then
            echo "Jenkins is already deployed"
          else 
            echo "Installing Jenkins .... // ...." 
            cat ${{ github.workspace }}/install_jenkins_dummy.sh | ssh k3s_server 'bash -s'
          fi;